name: 'Make Blender Test Matrix'
description: 'Generates a test matrix based on recent Blender releases'
outputs:
  matrix:
    description: 'The generated test matrix'
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: 'composite'

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'blenderkit/get-blender-test-matrix'

    - name: Generate Matrix
      shell: bash
      run: |
        MATRIX=$(python ${{ github.workspace }}/get-releases.py)
        echo "MATRIX_OUTPUT=$MATRIX" >> $GITHUB_ENV

    - name: Set action output
      shell: bash
      id: set-output
      run: echo "::set-output name=matrix::$MATRIX_OUTPUT"
