name: 'Make Blender Test Matrix'
description: 'Generates a test matrix based on recent Blender releases'
outputs:
  matrix:
    description: 'The generated test matrix'
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: 'composite'
  
  steps:
    - name: Generate Matrix
      run: |
        MATRIX=$(python ./path-to-your-script.py)
        echo "MATRIX_OUTPUT=$MATRIX" >> $GITHUB_ENV

    - name: Set action output
      id: set-output
      run: echo "::set-output name=matrix::$MATRIX_OUTPUT"
